feat: table support polling
ant-design/pro-components pull request #1097
Opened 2020-11-26 08:44 UTC by hengkx

ref #1096

2020-11-26 08:48 UTC, hengkx commented
eslint全不对？

2020-11-26 14:48 UTC, chenshuai2144 commented on packages/table/src/demos/pollinga.tsx
> +      polling={5000}
支持一下function，有时候需要根据 dataSource 里面的某些值来保证是不是要轮询

2020-11-26 14:49 UTC, chenshuai2144 requested changes
添加一下文档

2020-11-26 14:51 UTC, hengkx commented on packages/table/src/demos/pollinga.tsx
> +      polling={5000}
什么类型的 function 我现在 只用到了 这个 ，没思路

2020-11-26 14:51 UTC, chenshuai2144 commented
```
 packages/table/src/demos/pollinga.tsx:1:17
  ⚠   96:9   Unexpected console statement.                                  no-console
  ✖    1:17  useEffect is defined but never used.                           @typescript-eslint/no-unused-vars
  ✖    1:28  useRef is defined but never used.                              @typescript-eslint/no-unused-vars
  ✖    4:32  ActionType is defined but never used.                          @typescript-eslint/no-unused-vars
```

2020-11-26 14:53 UTC, chenshuai2144 commented on packages/table/src/demos/pollinga.tsx
> +      polling={5000}
```tsx
polling={(dataSource)=>{
    if(dataSource.some(item=>item.status!=="running")){
      return "5000"
    }
    return false
}}
```

2020-11-26 14:55 UTC, hengkx commented on packages/table/src/demos/pollinga.tsx
> +      polling={5000}
ok 我明天改一下

2020-11-26 15:18 UTC, hengkx commented
table打包的 体积 有点大啊

2020-11-27 07:37 UTC, chenshuai2144 commented on packages/table/src/typing.ts
> +  reload: (loading?: boolean) => Promise<void>;
不要搞这种 api，精良 api 是受控的

2020-11-27 07:42 UTC, hengkx commented on packages/table/src/typing.ts
> +  reload: (loading?: boolean) => Promise<void>;
这本来就是 方法 哪有什么 可不可控

2020-11-27 09:06 UTC, chenshuai2144 commented on packages/table/src/typing.ts
> +  reload: (loading?: boolean) => Promise<void>;
polling 默认 没有 loading 好了

2020-11-27 09:09 UTC, hengkx commented on packages/table/src/typing.ts
> +  reload: (loading?: boolean) => Promise<void>;
polling 默认 本来 就没 loading , 在table 里面调用了这个方法

2020-11-27 09:10 UTC, hengkx commented on packages/table/src/typing.ts
> +  reload: (loading?: boolean) => Promise<void>;
我自己 内部 业务 想办法 实现 吧

2020-12-18 06:33 UTC, closed without merging

2024-08-30 06:20 UTC, xiehuiqi220 commented
为什么polling这个特性在官方文档没有，实际代码却有这功能