fix(layout): Support using GlobalHeader prefixCls
ant-design/pro-components pull request #411
Opened 2020-09-07 10:42 UTC by ntfs32

2020-09-08 05:23 UTC, chenshuai2144 commented on .eslintrc.js
> +    'no-console': 'off',
为什么要关掉？

2020-09-08 05:24 UTC, ntfs32 commented on .eslintrc.js
> +    'no-console': 'off',
现在代码里面console很多，要么都都整体去掉吧

2020-09-08 08:02 UTC, ntfs32 commented
@chenshuai2144  迫切等待更新...

2020-09-08 08:35 UTC, chenshuai2144 commented on .eslintrc.js
> +    'no-console': 'off',
warning 没事的

2020-09-08 08:36 UTC, chenshuai2144 commented on .eslintrc.js
> +    'no-console': 'off',
```
'import/no-extraneous-dependencies': 0,
    'import/no-unresolved': 0,
```
这些也没必要去掉

2020-09-08 08:36 UTC, chenshuai2144 commented
加个测试用例呢？ 我可以专门给你发个版本

2020-09-08 08:46 UTC, ntfs32 commented on .eslintrc.js
> +    'no-console': 'off',
这俩 格式化换行了而已

2020-09-09 01:30 UTC, hengkx commented on .eslintrc.js
> +    'no-console': 'off',
'no-console': 'off', 这个去掉吧

2020-09-09 01:36 UTC, hengkx requested changes

2020-09-09 01:36 UTC, hengkx commented on packages/layout/src/TopNavHeader/index.tsx
> +  const prefixCls = `${props.prefixCls || 'ant-pro'}-top-nav-header`;
https://github.com/ant-design/ant-design/blob/master/components/config-provider/index.tsx#L68

第二个参数是自定义前缀

2020-09-09 02:02 UTC, ntfs32 commented on packages/layout/src/TopNavHeader/index.tsx
> +  const prefixCls = `${props.prefixCls || 'ant-pro'}-top-nav-header`;
@hengkx  是为了统一使用 BasicLayout 传递的prefixCls，默认传递值为ant-pro

2020-09-09 03:09 UTC, chenshuai2144 commented on .eslintrc.js
> +    'no-console': 'off',
把 console 删掉就可以了

2020-09-09 03:10 UTC, chenshuai2144 requested changes
删掉 'no-console': 'off',

2020-09-09 05:22 UTC, chenshuai2144 commented
注意一下你的commit name 好像有点问题

2020-09-09 05:22 UTC, merged

2020-09-09 08:09 UTC, ntfs32 commented
@chenshuai2144  可否发布一个fix版本？

2020-09-09 14:33 UTC, chenshuai2144 commented
明天发